export type CountryOption = {
  value: string;
  label: string;
};

/** Closest-city options keyed by country value. */
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Argentina": [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Mar del Plata",
    "San Miguel de Tucumán",
    "Salta",
    "Santa Fe",
    "Neuquén"
  ],
  "Australia": [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Newcastle",
    "Hobart",
    "Geelong"
  ],
  "Brazil": [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Belo Horizonte",
    "Curitiba",
    "Porto Alegre",
    "Recife",
    "Salvador",
    "Fortaleza",
    "Campinas",
    "Manaus",
    "Florianópolis"
  ],
  "Bulgaria": [
    "Sofia",
    "Plovdiv",
    "Varna",
    "Burgas",
    "Ruse",
    "Stara Zagora",
    "Pleven",
    "Sliven",
    "Dobrich",
    "Shumen"
  ],
  "Canada": [
    "Toronto, ON",
    "Vancouver, BC",
    "Montreal, QC",
    "Calgary, AB",
    "Ottawa, ON",
    "Edmonton, AB",
    "Winnipeg, MB",
    "Quebec City, QC",
    "Hamilton, ON",
    "Kitchener-Waterloo, ON",
    "London, ON",
    "Victoria, BC",
    "Halifax, NS",
    "Mississauga, ON"
  ],
  "China": [
    "Beijing",
    "Shanghai",
    "Shenzhen",
    "Hangzhou",
    "Guangzhou",
    "Chengdu",
    "Xi'an",
    "Nanjing",
    "Wuhan",
    "Suzhou",
    "Tianjin",
    "Chongqing",
    "Dongguan",
    "Xiamen"
  ],
  "Colombia": [
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
    "Cartagena",
    "Bucaramanga",
    "Pereira",
    "Manizales",
    "Cúcuta",
    "Ibagué"
  ],
  "Costa Rica": [
    "San José",
    "Heredia",
    "Alajuela",
    "Cartago",
    "Liberia",
    "Puntarenas",
    "Limón",
    "Escazú",
    "Curridabat",
    "Santa Ana"
  ],
  "Czechia": [
    "Prague",
    "Brno",
    "Ostrava",
    "Plzeň",
    "Liberec",
    "Olomouc",
    "České Budějovice",
    "Hradec Králové",
    "Ústí nad Labem",
    "Pardubice"
  ],
  "Egypt": [
    "Cairo",
    "Alexandria",
    "Giza",
    "Sharm El Sheikh",
    "Port Said",
    "Suez",
    "Luxor",
    "Aswan",
    "Mansoura",
    "Tanta"
  ],
  "France": [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Nantes",
    "Lille",
    "Bordeaux",
    "Strasbourg",
    "Montpellier",
    "Rennes",
    "Grenoble"
  ],
  "Germany": [
    "Berlin",
    "Hamburg",
    "Munich",
    "Frankfurt",
    "Cologne",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Nuremberg",
    "Hanover",
    "Dresden"
  ],
  "Hungary": [
    "Budapest",
    "Debrecen",
    "Szeged",
    "Miskolc",
    "Pécs",
    "Győr",
    "Nyíregyháza",
    "Kecskemét",
    "Székesfehérvár",
    "Szombathely"
  ],
  "India": [
    "Bengaluru",
    "Hyderabad",
    "Mumbai",
    "New Delhi",
    "Pune",
    "Chennai",
    "Noida",
    "Gurugram",
    "Ahmedabad",
    "Kochi",
    "Kolkata",
    "Jaipur",
    "Chandigarh",
    "Coimbatore",
    "Indore",
    "Thiruvananthapuram"
  ],
  "Indonesia": [
    "Jakarta",
    "Bandung",
    "Surabaya",
    "Yogyakarta",
    "Medan",
    "Semarang",
    "Makassar",
    "Denpasar",
    "Bogor",
    "Malang"
  ],
  "Ireland": [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
    "Waterford",
    "Kilkenny",
    "Sligo",
    "Dundalk",
    "Drogheda",
    "Athlone"
  ],
  "Israel": [
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
    "Herzliya",
    "Beersheba",
    "Netanya",
    "Rishon LeZion",
    "Petah Tikva",
    "Ashdod",
    "Ramat Gan"
  ],
  "Japan": [
    "Tokyo",
    "Osaka",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
    "Kyoto",
    "Kawasaki",
    "Saitama",
    "Hiroshima",
    "Sendai"
  ],
  "Malaysia": [
    "Kuala Lumpur",
    "Penang",
    "Johor Bahru",
    "Cyberjaya",
    "Petaling Jaya",
    "Shah Alam",
    "Ipoh",
    "Malacca",
    "Kota Kinabalu",
    "Kuching"
  ],
  "Mexico": [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Querétaro",
    "Tijuana",
    "Puebla",
    "León",
    "Mérida",
    "Cancún",
    "Toluca",
    "Ciudad Juárez",
    "Aguascalientes"
  ],
  "Netherlands": [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
    "Tilburg",
    "Almere",
    "Breda",
    "Nijmegen"
  ],
  "Nigeria": [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Ibadan",
    "Kano",
    "Benin City",
    "Enugu",
    "Kaduna",
    "Abeokuta",
    "Ilorin"
  ],
  "Pakistan": [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Faisalabad",
    "Peshawar",
    "Multan",
    "Hyderabad",
    "Gujranwala",
    "Sialkot"
  ],
  "Philippines": [
    "Manila",
    "Quezon City",
    "Makati",
    "Taguig",
    "Cebu",
    "Davao",
    "Iloilo",
    "Cagayan de Oro",
    "Bacolod",
    "Baguio",
    "Pasig",
    "Parañaque"
  ],
  "Poland": [
    "Warsaw",
    "Kraków",
    "Wrocław",
    "Gdańsk",
    "Poznań",
    "Łódź",
    "Katowice",
    "Lublin",
    "Białystok",
    "Szczecin",
    "Bydgoszcz",
    "Rzeszów"
  ],
  "Portugal": [
    "Lisbon",
    "Porto",
    "Braga",
    "Coimbra",
    "Faro",
    "Aveiro",
    "Setúbal",
    "Funchal",
    "Évora",
    "Guimarães"
  ],
  "Romania": [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Brașov",
    "Constanța",
    "Craiova",
    "Galați",
    "Oradea",
    "Sibiu"
  ],
  "Singapore": [
    "Central Area",
    "Marina Bay",
    "Orchard",
    "Jurong East",
    "Tampines",
    "Woodlands",
    "Punggol",
    "Queenstown",
    "Bukit Timah",
    "Changi"
  ],
  "South Africa": [
    "Cape Town",
    "Johannesburg",
    "Pretoria",
    "Durban",
    "Port Elizabeth",
    "Bloemfontein",
    "East London",
    "Stellenbosch",
    "Centurion",
    "Sandton"
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daejeon",
    "Daegu",
    "Gwangju",
    "Suwon",
    "Ulsan",
    "Seongnam",
    "Changwon"
  ],
  "Spain": [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Málaga",
    "Bilbao",
    "Zaragoza",
    "Murcia",
    "Palma",
    "Alicante",
    "Granada",
    "Vigo"
  ],
  "Taiwan": [
    "Taipei",
    "New Taipei",
    "Hsinchu",
    "Taichung",
    "Kaohsiung",
    "Tainan",
    "Taoyuan",
    "Keelung",
    "Chiayi",
    "Hualien"
  ],
  "Thailand": [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
    "Pattaya",
    "Nonthaburi",
    "Hat Yai",
    "Khon Kaen",
    "Nakhon Ratchasima",
    "Chiang Rai",
    "Udon Thani"
  ],
  "Ukraine": [
    "Kyiv",
    "Lviv",
    "Kharkiv",
    "Odesa",
    "Dnipro",
    "Zaporizhzhia",
    "Vinnytsia",
    "Ivano-Frankivsk",
    "Poltava",
    "Chernivtsi"
  ],
  "United Arab Emirates": [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Ajman",
    "Ras Al Khaimah",
    "Fujairah",
    "Al Ain",
    "Um Al Quwain",
    "Dubai Marina",
    "Business Bay"
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Bristol",
    "Leeds",
    "Glasgow",
    "Cambridge",
    "Oxford",
    "Reading",
    "Newcastle",
    "Liverpool",
    "Sheffield",
    "Cardiff",
    "Belfast"
  ],
  "United States": [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Dallas, TX",
    "Houston, TX",
    "Atlanta, GA",
    "Washington, DC",
    "Miami, FL",
    "Philadelphia, PA",
    "Phoenix, AZ",
    "Boston, MA",
    "Riverside, CA",
    "San Francisco, CA",
    "Detroit, MI",
    "Seattle, WA",
    "Minneapolis, MN",
    "Tampa, FL",
    "San Diego, CA",
    "Denver, CO",
    "Orlando, FL",
    "Charlotte, NC",
    "Baltimore, MD",
    "St. Louis, MO",
    "San Antonio, TX",
    "Austin, TX",
    "Portland, OR",
    "Sacramento, CA",
    "Pittsburgh, PA",
    "Las Vegas, NV",
    "Cincinnati, OH",
    "Kansas City, MO",
    "Columbus, OH",
    "Indianapolis, IN",
    "Nashville, TN",
    "Cleveland, OH",
    "San Jose, CA",
    "Jacksonville, FL",
    "Providence, RI",
    "Raleigh, NC",
    "Milwaukee, WI",
    "Oklahoma City, OK",
    "Louisville, KY",
    "Richmond, VA",
    "Memphis, TN",
    "Salt Lake City, UT",
    "Fresno, CA",
    "Birmingham, AL",
    "Grand Rapids, MI",
    "Hartford, CT",
    "Buffalo, NY",
    "Tucson, AZ",
    "Tulsa, OK",
    "Rochester, NY",
    "Greenville, SC",
    "Omaha, NE",
    "Honolulu, HI",
    "Bridgeport, CT",
    "New Orleans, LA",
    "Knoxville, TN",
    "North Port, FL",
    "Bakersfield, CA",
    "Albuquerque, NM",
    "McAllen, TX",
    "Albany, NY",
    "Charleston, SC",
    "Baton Rouge, LA",
    "Worcester, MA",
    "Allentown, PA",
    "El Paso, TX",
    "Columbia, SC",
    "Cape Coral, FL",
    "Lakeland, FL",
    "Boise, ID",
    "Oxnard, CA",
    "Dayton, OH",
    "Stockton, CA",
    "Greensboro, NC",
    "Colorado Springs, CO",
    "Little Rock, AR",
    "Provo, UT",
    "Des Moines, IA",
    "Deltona, FL",
    "Poughkeepsie, NY",
    "Winston-Salem, NC",
    "Madison, WI",
    "Akron, OH",
    "Ogden, UT",
    "Palm Bay, FL",
    "Wichita, KS",
    "Syracuse, NY",
    "Augusta, GA",
    "Durham, NC",
    "Fayetteville, AR",
    "Harrisburg, PA",
    "Jackson, MS",
    "Spokane, WA",
    "Toledo, OH",
    "Chattanooga, TN",
    "New Haven, CT",
    "Reno, NV",
    "Portland, ME",
    "Scranton, PA",
    "Port St. Lucie, FL",
    "Lancaster, PA",
    "Modesto, CA",
    "Huntsville, AL",
    "Pensacola, FL",
    "Lexington, KY",
    "Killeen, TX",
    "Springfield, MO",
    "Wilmington, NC",
    "Santa Rosa, CA",
    "Visalia, CA",
    "Lansing, MI",
    "York, PA",
    "Fort Wayne, IN",
    "Springfield, MA",
    "Waterbury, CT",
    "Vallejo, CA",
    "Corpus Christi, TX",
    "Salem, OR",
    "Ocala, FL",
    "Santa Maria, CA",
    "Reading, PA",
    "Savannah, GA",
    "Brownsville, TX",
    "Salinas, CA",
    "Manchester, NH",
    "Gulfport, MS",
    "Myrtle Beach, SC",
    "Lafayette, LA",
    "Youngstown, OH",
    "Asheville, NC",
    "Naples, FL",
    "Mobile, AL",
    "Spartanburg, SC",
    "Anchorage, AK",
    "Flint, MI",
    "Canton, OH",
    "Beaumont, TX",
    "Trenton, NJ",
    "Tallahassee, FL",
    "Fayetteville, NC",
    "Montgomery, AL",
    "Shreveport, LA",
    "Eugene, OR",
    "Davenport, IA",
    "Greeley, CO",
    "Fort Collins, CO",
    "Hickory, NC",
    "Atlantic City, NJ",
    "Ann Arbor, MI",
    "Lubbock, TX",
    "Huntington, WV",
    "Peoria, IL",
    "Gainesville, FL",
    "Lincoln, NE",
    "Clarksville, TN",
    "Rockford, IL",
    "Green Bay, WI",
    "Boulder, CO",
    "Columbus, GA",
    "South Bend, IN",
    "Kennewick, WA",
    "Roanoke, VA",
    "Hagerstown, MD",
    "Crestview, FL",
    "Kingsport, TN",
    "Sioux Falls, SD",
    "Waco, TX",
    "Olympia, WA",
    "Longview, TX",
    "Merced, CA",
    "College Station, TX",
    "Utica, NY",
    "Norwich, CT",
    "Bremerton, WA",
    "San Luis Obispo, CA",
    "Tuscaloosa, AL",
    "Laredo, TX",
    "Duluth, MN",
    "Cedar Rapids, IA",
    "Slidell, LA",
    "Amarillo, TX",
    "Evansville, IN",
    "Fargo, ND",
    "Lynchburg, VA",
    "Daphne, AL",
    "Bend, OR",
    "Erie, PA",
    "Kalamazoo, MI",
    "Yakima, WA",
    "Santa Cruz, CA",
    "Prescott Valley, AZ",
    "Tyler, TX",
    "Appleton, WI",
    "Lake Charles, LA",
    "Binghamton, NY",
    "Hilton Head Island, SC",
    "Champaign, IL"
  ],
  "Vietnam": [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
    "Hai Phong",
    "Can Tho",
    "Nha Trang",
    "Hue",
    "Bien Hoa",
    "Vung Tau",
    "Buon Ma Thuot",
    "Qui Nhon",
    "Ha Long"
  ]
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  ...Object.keys(CITIES_BY_COUNTRY)
    .sort((a, b) => a.localeCompare(b))
    .map((name) => ({ value: name, label: name })),
  { value: "Other", label: "Other / not listed" },
];

export const OTHER_CITY_VALUE = "__other__";

export function citiesForCountry(country: string): string[] {
  return CITIES_BY_COUNTRY[country] ?? [];
}

