export type CountryOption = {
  value: string;
  label: string;
};

/** Closest-city options keyed by country value. */
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "Argentina": [
    "Buenos Aires",
    "Córdoba",
    "La Plata",
    "Mar del Plata",
    "Mendoza",
    "Neuquén",
    "Rosario",
    "Salta",
    "San Miguel de Tucumán",
    "Santa Fe"
  ],
  "Australia": [
    "Adelaide",
    "Brisbane",
    "Canberra",
    "Geelong",
    "Gold Coast",
    "Hobart",
    "Melbourne",
    "Newcastle",
    "Perth",
    "Sydney"
  ],
  "Brazil": [
    "Belo Horizonte",
    "Brasília",
    "Campinas",
    "Curitiba",
    "Florianópolis",
    "Fortaleza",
    "Manaus",
    "Porto Alegre",
    "Recife",
    "Rio de Janeiro",
    "Salvador",
    "São Paulo"
  ],
  "Bulgaria": [
    "Burgas",
    "Dobrich",
    "Pleven",
    "Plovdiv",
    "Ruse",
    "Shumen",
    "Sliven",
    "Sofia",
    "Stara Zagora",
    "Varna"
  ],
  "Canada": [
    "Calgary, AB",
    "Edmonton, AB",
    "Halifax, NS",
    "Hamilton, ON",
    "Kitchener-Waterloo, ON",
    "London, ON",
    "Mississauga, ON",
    "Montreal, QC",
    "Ottawa, ON",
    "Quebec City, QC",
    "Toronto, ON",
    "Vancouver, BC",
    "Victoria, BC",
    "Winnipeg, MB"
  ],
  "China": [
    "Beijing",
    "Chengdu",
    "Chongqing",
    "Dongguan",
    "Guangzhou",
    "Hangzhou",
    "Nanjing",
    "Shanghai",
    "Shenzhen",
    "Suzhou",
    "Tianjin",
    "Wuhan",
    "Xi'an",
    "Xiamen"
  ],
  "Colombia": [
    "Barranquilla",
    "Bogotá",
    "Bucaramanga",
    "Cali",
    "Cartagena",
    "Cúcuta",
    "Ibagué",
    "Manizales",
    "Medellín",
    "Pereira"
  ],
  "Costa Rica": [
    "Alajuela",
    "Cartago",
    "Curridabat",
    "Escazú",
    "Heredia",
    "Liberia",
    "Limón",
    "Puntarenas",
    "San José",
    "Santa Ana"
  ],
  "Czechia": [
    "Brno",
    "Hradec Králové",
    "Liberec",
    "Olomouc",
    "Ostrava",
    "Pardubice",
    "Plzeň",
    "Prague",
    "Ústí nad Labem",
    "České Budějovice"
  ],
  "Egypt": [
    "Alexandria",
    "Aswan",
    "Cairo",
    "Giza",
    "Luxor",
    "Mansoura",
    "Port Said",
    "Sharm El Sheikh",
    "Suez",
    "Tanta"
  ],
  "France": [
    "Bordeaux",
    "Grenoble",
    "Lille",
    "Lyon",
    "Marseille",
    "Montpellier",
    "Nantes",
    "Nice",
    "Paris",
    "Rennes",
    "Strasbourg",
    "Toulouse"
  ],
  "Germany": [
    "Berlin",
    "Cologne",
    "Dortmund",
    "Dresden",
    "Düsseldorf",
    "Essen",
    "Frankfurt",
    "Hamburg",
    "Hanover",
    "Leipzig",
    "Munich",
    "Nuremberg",
    "Stuttgart"
  ],
  "Hungary": [
    "Budapest",
    "Debrecen",
    "Győr",
    "Kecskemét",
    "Miskolc",
    "Nyíregyháza",
    "Pécs",
    "Szeged",
    "Szombathely",
    "Székesfehérvár"
  ],
  "India": [
    "Ahmedabad",
    "Bengaluru",
    "Chandigarh",
    "Chennai",
    "Coimbatore",
    "Gurugram",
    "Hyderabad",
    "Indore",
    "Jaipur",
    "Kochi",
    "Kolkata",
    "Mumbai",
    "New Delhi",
    "Noida",
    "Pune",
    "Thiruvananthapuram"
  ],
  "Indonesia": [
    "Bandung",
    "Bogor",
    "Denpasar",
    "Jakarta",
    "Makassar",
    "Malang",
    "Medan",
    "Semarang",
    "Surabaya",
    "Yogyakarta"
  ],
  "Ireland": [
    "Athlone",
    "Cork",
    "Drogheda",
    "Dublin",
    "Dundalk",
    "Galway",
    "Kilkenny",
    "Limerick",
    "Sligo",
    "Waterford"
  ],
  "Israel": [
    "Ashdod",
    "Beersheba",
    "Haifa",
    "Herzliya",
    "Jerusalem",
    "Netanya",
    "Petah Tikva",
    "Ramat Gan",
    "Rishon LeZion",
    "Tel Aviv"
  ],
  "Japan": [
    "Fukuoka",
    "Hiroshima",
    "Kawasaki",
    "Kobe",
    "Kyoto",
    "Nagoya",
    "Osaka",
    "Saitama",
    "Sapporo",
    "Sendai",
    "Tokyo",
    "Yokohama"
  ],
  "Malaysia": [
    "Cyberjaya",
    "Ipoh",
    "Johor Bahru",
    "Kota Kinabalu",
    "Kuala Lumpur",
    "Kuching",
    "Malacca",
    "Penang",
    "Petaling Jaya",
    "Shah Alam"
  ],
  "Mexico": [
    "Aguascalientes",
    "Cancún",
    "Ciudad Juárez",
    "Guadalajara",
    "León",
    "Mexico City",
    "Monterrey",
    "Mérida",
    "Puebla",
    "Querétaro",
    "Tijuana",
    "Toluca"
  ],
  "Netherlands": [
    "Almere",
    "Amsterdam",
    "Breda",
    "Eindhoven",
    "Groningen",
    "Nijmegen",
    "Rotterdam",
    "The Hague",
    "Tilburg",
    "Utrecht"
  ],
  "Nigeria": [
    "Abeokuta",
    "Abuja",
    "Benin City",
    "Enugu",
    "Ibadan",
    "Ilorin",
    "Kaduna",
    "Kano",
    "Lagos",
    "Port Harcourt"
  ],
  "Pakistan": [
    "Faisalabad",
    "Gujranwala",
    "Hyderabad",
    "Islamabad",
    "Karachi",
    "Lahore",
    "Multan",
    "Peshawar",
    "Rawalpindi",
    "Sialkot"
  ],
  "Philippines": [
    "Bacolod",
    "Baguio",
    "Cagayan de Oro",
    "Cebu",
    "Davao",
    "Iloilo",
    "Makati",
    "Manila",
    "Parañaque",
    "Pasig",
    "Quezon City",
    "Taguig"
  ],
  "Poland": [
    "Białystok",
    "Bydgoszcz",
    "Gdańsk",
    "Katowice",
    "Kraków",
    "Lublin",
    "Poznań",
    "Rzeszów",
    "Szczecin",
    "Warsaw",
    "Wrocław",
    "Łódź"
  ],
  "Portugal": [
    "Aveiro",
    "Braga",
    "Coimbra",
    "Faro",
    "Funchal",
    "Guimarães",
    "Lisbon",
    "Porto",
    "Setúbal",
    "Évora"
  ],
  "Romania": [
    "Brașov",
    "Bucharest",
    "Cluj-Napoca",
    "Constanța",
    "Craiova",
    "Galați",
    "Iași",
    "Oradea",
    "Sibiu",
    "Timișoara"
  ],
  "Singapore": [
    "Bukit Timah",
    "Central Area",
    "Changi",
    "Jurong East",
    "Marina Bay",
    "Orchard",
    "Punggol",
    "Queenstown",
    "Tampines",
    "Woodlands"
  ],
  "South Africa": [
    "Bloemfontein",
    "Cape Town",
    "Centurion",
    "Durban",
    "East London",
    "Johannesburg",
    "Port Elizabeth",
    "Pretoria",
    "Sandton",
    "Stellenbosch"
  ],
  "South Korea": [
    "Busan",
    "Changwon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Incheon",
    "Seongnam",
    "Seoul",
    "Suwon",
    "Ulsan"
  ],
  "Spain": [
    "Alicante",
    "Barcelona",
    "Bilbao",
    "Granada",
    "Madrid",
    "Murcia",
    "Málaga",
    "Palma",
    "Seville",
    "Valencia",
    "Vigo",
    "Zaragoza"
  ],
  "Taiwan": [
    "Chiayi",
    "Hsinchu",
    "Hualien",
    "Kaohsiung",
    "Keelung",
    "New Taipei",
    "Taichung",
    "Tainan",
    "Taipei",
    "Taoyuan"
  ],
  "Thailand": [
    "Bangkok",
    "Chiang Mai",
    "Chiang Rai",
    "Hat Yai",
    "Khon Kaen",
    "Nakhon Ratchasima",
    "Nonthaburi",
    "Pattaya",
    "Phuket",
    "Udon Thani"
  ],
  "Ukraine": [
    "Chernivtsi",
    "Dnipro",
    "Ivano-Frankivsk",
    "Kharkiv",
    "Kyiv",
    "Lviv",
    "Odesa",
    "Poltava",
    "Vinnytsia",
    "Zaporizhzhia"
  ],
  "United Arab Emirates": [
    "Abu Dhabi",
    "Ajman",
    "Al Ain",
    "Business Bay",
    "Dubai",
    "Dubai Marina",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Um Al Quwain"
  ],
  "United Kingdom": [
    "Belfast",
    "Birmingham",
    "Bristol",
    "Cambridge",
    "Cardiff",
    "Edinburgh",
    "Glasgow",
    "Leeds",
    "Liverpool",
    "London",
    "Manchester",
    "Newcastle",
    "Oxford",
    "Reading",
    "Sheffield"
  ],
  "United States": [
    "Akron, OH",
    "Albany, NY",
    "Albuquerque, NM",
    "Allentown, PA",
    "Amarillo, TX",
    "Anchorage, AK",
    "Ann Arbor, MI",
    "Appleton, WI",
    "Asheville, NC",
    "Atlanta, GA",
    "Atlantic City, NJ",
    "Augusta, GA",
    "Austin, TX",
    "Bakersfield, CA",
    "Baltimore, MD",
    "Baton Rouge, LA",
    "Beaumont, TX",
    "Bend, OR",
    "Binghamton, NY",
    "Birmingham, AL",
    "Boise, ID",
    "Boston, MA",
    "Boulder, CO",
    "Bremerton, WA",
    "Bridgeport, CT",
    "Brownsville, TX",
    "Buffalo, NY",
    "Canton, OH",
    "Cape Coral, FL",
    "Cedar Rapids, IA",
    "Champaign, IL",
    "Charleston, SC",
    "Charlotte, NC",
    "Chattanooga, TN",
    "Chicago, IL",
    "Cincinnati, OH",
    "Clarksville, TN",
    "Cleveland, OH",
    "College Station, TX",
    "Colorado Springs, CO",
    "Columbia, SC",
    "Columbus, GA",
    "Columbus, OH",
    "Corpus Christi, TX",
    "Crestview, FL",
    "Dallas, TX",
    "Daphne, AL",
    "Davenport, IA",
    "Dayton, OH",
    "Deltona, FL",
    "Denver, CO",
    "Des Moines, IA",
    "Detroit, MI",
    "Duluth, MN",
    "Durham, NC",
    "El Paso, TX",
    "Erie, PA",
    "Eugene, OR",
    "Evansville, IN",
    "Fargo, ND",
    "Fayetteville, AR",
    "Fayetteville, NC",
    "Flint, MI",
    "Fort Collins, CO",
    "Fort Wayne, IN",
    "Fresno, CA",
    "Gainesville, FL",
    "Grand Rapids, MI",
    "Greeley, CO",
    "Green Bay, WI",
    "Greensboro, NC",
    "Greenville, SC",
    "Gulfport, MS",
    "Hagerstown, MD",
    "Harrisburg, PA",
    "Hartford, CT",
    "Hickory, NC",
    "Hilton Head Island, SC",
    "Honolulu, HI",
    "Houston, TX",
    "Huntington, WV",
    "Huntsville, AL",
    "Indianapolis, IN",
    "Jackson, MS",
    "Jacksonville, FL",
    "Kalamazoo, MI",
    "Kansas City, MO",
    "Kennewick, WA",
    "Killeen, TX",
    "Kingsport, TN",
    "Knoxville, TN",
    "Lafayette, LA",
    "Lake Charles, LA",
    "Lakeland, FL",
    "Lancaster, PA",
    "Lansing, MI",
    "Laredo, TX",
    "Las Vegas, NV",
    "Lexington, KY",
    "Lincoln, NE",
    "Little Rock, AR",
    "Longview, TX",
    "Los Angeles, CA",
    "Louisville, KY",
    "Lubbock, TX",
    "Lynchburg, VA",
    "Madison, WI",
    "Manchester, NH",
    "McAllen, TX",
    "Memphis, TN",
    "Merced, CA",
    "Miami, FL",
    "Milwaukee, WI",
    "Minneapolis, MN",
    "Mobile, AL",
    "Modesto, CA",
    "Montgomery, AL",
    "Myrtle Beach, SC",
    "Naples, FL",
    "Nashville, TN",
    "New Haven, CT",
    "New Orleans, LA",
    "New York, NY",
    "North Port, FL",
    "Norwich, CT",
    "Ocala, FL",
    "Ogden, UT",
    "Oklahoma City, OK",
    "Olympia, WA",
    "Omaha, NE",
    "Orlando, FL",
    "Oxnard, CA",
    "Palm Bay, FL",
    "Pensacola, FL",
    "Peoria, IL",
    "Philadelphia, PA",
    "Phoenix, AZ",
    "Pittsburgh, PA",
    "Port St. Lucie, FL",
    "Portland, ME",
    "Portland, OR",
    "Poughkeepsie, NY",
    "Prescott Valley, AZ",
    "Providence, RI",
    "Provo, UT",
    "Raleigh, NC",
    "Reading, PA",
    "Reno, NV",
    "Richmond, VA",
    "Riverside, CA",
    "Roanoke, VA",
    "Rochester, NY",
    "Rockford, IL",
    "Sacramento, CA",
    "Salem, OR",
    "Salinas, CA",
    "Salt Lake City, UT",
    "San Antonio, TX",
    "San Diego, CA",
    "San Francisco, CA",
    "San Jose, CA",
    "San Luis Obispo, CA",
    "Santa Cruz, CA",
    "Santa Maria, CA",
    "Santa Rosa, CA",
    "Savannah, GA",
    "Scranton, PA",
    "Seattle, WA",
    "Shreveport, LA",
    "Sioux Falls, SD",
    "Slidell, LA",
    "South Bend, IN",
    "Spartanburg, SC",
    "Spokane, WA",
    "Springfield, MA",
    "Springfield, MO",
    "St. Louis, MO",
    "Stockton, CA",
    "Syracuse, NY",
    "Tallahassee, FL",
    "Tampa, FL",
    "Toledo, OH",
    "Trenton, NJ",
    "Tucson, AZ",
    "Tulsa, OK",
    "Tuscaloosa, AL",
    "Tyler, TX",
    "Utica, NY",
    "Vallejo, CA",
    "Visalia, CA",
    "Waco, TX",
    "Washington, DC",
    "Waterbury, CT",
    "Wichita, KS",
    "Wilmington, NC",
    "Winston-Salem, NC",
    "Worcester, MA",
    "Yakima, WA",
    "York, PA",
    "Youngstown, OH"
  ],
  "Vietnam": [
    "Bien Hoa",
    "Buon Ma Thuot",
    "Can Tho",
    "Da Nang",
    "Ha Long",
    "Hai Phong",
    "Hanoi",
    "Ho Chi Minh City",
    "Hue",
    "Nha Trang",
    "Qui Nhon",
    "Vung Tau"
  ]
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  ...Object.keys(CITIES_BY_COUNTRY)
    .sort((a, b) => a.localeCompare(b))
    .map((name) => ({ value: name, label: name })),
  { value: "Other", label: "Other / not listed" },
];

export const OTHER_CITY_VALUE = "__other__";

export function citiesForCountry(country: string): string[] {
  return CITIES_BY_COUNTRY[country] ?? [];
}

